output_folder: application_overview

outputs:

  - file_name: application_overview.xlsx
    columns:
      - Application Name
      - Application Categories
      - Company
    filter:
      Company: BCP
      Application Categories: Business Application